name: build and push relay docker image

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/clipboard-sync-relay:latest ./clipboard-sync-relay

    - name: push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/clipboard-sync-relay:latest
